name: Unit tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit_tests:

    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    strategy:
      matrix:
        combos: [{group: 1, python_version: '3.9'},
                 {group: 2, python_version: '3.10'},
                 {group: 3, python_version: '3.11'},
                 {group: 4, python_version: '3.12'},
                 {group: 5, python_version: '3.12'},
                 {group: 6, python_version: '3.12'},
                 {group: 7, python_version: '3.12'},
                 {group: 8, python_version: '3.12'}]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.combos.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.combos.python_version }}

      - name: Restore Python environment cache
        id: restore-env
        uses: actions/cache/restore@v4
        with:
          path: .venv-${{ matrix.combos.python_version }}
          key: ${{ runner.os }}-venv-${{ matrix.combos.python_version }}-${{ hashFiles('devtools/dev-requirements.txt', 'requirements.txt') }}

      - name: Set up virtual environment if not restored from cache
        if: steps.restore-env.outputs.cache-hit != 'true'
        run: |
          gh cache list
          python -m venv .venv-${{ matrix.combos.python_version }}
          source .venv-${{ matrix.combos.python_version }}/bin/activate
          python -m pip install --upgrade pip
          pip install -r devtools/dev-requirements.txt

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Test with pytest
        run: |
          source .venv-${{ matrix.combos.python_version }}/bin/activate
          pwd
          lscpu
          python -m pytest -v -m unit \
            --durations=0 \
            --cov-report xml:cov.xml \
            --cov-config=setup.cfg \
            --cov=desc/ \
            --mpl \
            --mpl-results-path=mpl_results.html \
            --mpl-generate-summary=html \
            --splits 8 \
            --group ${{ matrix.combos.group }} \
            --splitting-algorithm least_duration \
            --db ./prof.db
